# This file is exempted from License Regulations #
name: InfinityFree - Github Integration
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pull-from-server:
    if: github.event_name != 'pull_request' # skip on PRs to avoid FTP secrets exposure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install LFTP
        run: sudo apt-get install -y lftp

      - name: Download from InfinityFree
        run: |
          lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" ${{ secrets.FTP_HOST }} <<EOF
          mirror --verbose /htdocs ./htdocs --only-newer --parallel=5
          bye
          EOF

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Sync from InfinityFree"
          git push origin main

  push-to-server:
    if: github.event_name != 'pull_request' # skip on PRs to avoid FTP secrets exposure
    needs: pull-from-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
